### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by MarlBurroW** [bstascavage/plexHue#11]
Hello, 

Very nice job ! i've just some question.
- Is it possible to configure multiple plex clients ? because i'm using sometime the Chromecast, and sometime Plex for PS4.
- Is it possible to set the unique ID of the Light in the config file ? Because I think the name of the light is not the right way. 

Thanks

**Comment by bstascavage** [comment]
1.  Right now it supports just one.  Would multiple Plex clients trigger multiple light groups, or just one?  Regardless, open a ticket and I'll take a look, it shouldn't be hard
2.  I am a little confused by this.  Can you rephrase it?
