### ISSUE TITLE
Absolute path in plexHue DAEMON

### ISSUE THREAD

**Issue by johnagterdenbos** [bstascavage/plexHue#5]
When trying to start the plexHue service there is an error because the path is referring to:
DAEMON=/home/bstascav/plexHue/bin/plexHue.rb

The /home/bstascav bit should be relative

**Comment by bstascavage** [comment]
Good catch.  However, this is part of a bigger issue, in that I actually need to package this up into a .deb.  In till them, I'll need to think of a good work around.

**Comment by bstascavage** [comment]
This is now fixed
