### ISSUE TITLE
Support Plex Home

### ISSUE THREAD

**Issue by vwieczorek** [bstascavage/plexHue#7]
If Plex Home (https://blog.plex.tv/2014/11/20/introducing-plex-home/) is enabled, plexHue is not able to authenticate to the server to pull session status.

**Comment by bstascavage** [comment]
So Plex doesn't document their Web API, and I am having a hard time figuring out how their API is authenticated via Plex Home.  Let me play with it on my server and see if I can figure it out, but as of right now, I don't know how to implement this :(

**Comment by vwieczorek** [comment]
Thanks for looking into this. This forum post seems to detail how to acquire a plex token: https://forums.plex.tv/index.php/topic/129922-how-to-request-a-myplex-token-for-your-app/ I'm not sure it will help in this case or not.
