### ISSUE TITLE
PlexHue failed to start 

### ISSUE THREAD

**Issue by mar7ius** [bstascavage/plexHue#9]
Hi,

I got an issue when I'm trying to start PlexHue, 

service plexHue start
Starting PlexHue
service plexHue status
[FAIL] plexHue is not running ... failed!

**Comment by bstascavage** [comment]
There is a bug with the init script, where it is looking in the wrong place.  Edit line 20 from 'DAEMON=/home/bstascav/plexHue/bin/plexHue.rb' to 'DAEMON=<your path>'

**Comment by mar7ius** [comment]
Thank for the quick answer. However, still can't run the script, i've got some errors coming after the change.. any idea ? BTW thanks for this, it's a great project i've been looking for a long time ago!

![issue](https://cloud.githubusercontent.com/assets/10807969/6007802/46479c5e-ab1d-11e4-84c5-906c5730b516.png)

**Comment by bstascavage** [comment]
Lets start with the basics: can you run the script by hand, aka the plexHue.rb script?

Also, what OS are you on?

**Comment by MarcusAncus** [comment]
As you close the subject, i don’t know if you will see the answer so, I send it also by mail.

Regards.
Martial

"Thank for the quick answer. However, still can't run the script, i've got some errors coming after the change.. any idea ? BTW thanks for this, it's a great project i've been looking for a long time ago! "

**Comment by mar7ius** [comment]
No, the script won't run, i got this :

![issue 2](https://cloud.githubusercontent.com/assets/10807969/6008157/b76ffc12-ab1f-11e4-8938-95dc4f70e589.png)

Even when I force the ruby version with ruby1.9.3 command.

I'm running Debian on a Synology system via Chroot. I got to install a lot of dependencies and missing packages.. I Also try to run it on my mac, same issue with the /lib/init/vars.sh

**Comment by bstascavage** [comment]
What does your config.yaml look like?

**Comment by mar7ius** [comment]
![config](https://cloud.githubusercontent.com/assets/10807969/6008567/f83499c6-ab22-11e4-86e5-c9281ba34c49.png)

like that! I've tried with localhost instead of 10.0.0.5 but still the same

**Comment by bstascavage** [comment]
Remove the '<' and '>' from the machineIdentifier

**Comment by mar7ius** [comment]
yes it could be a good start ^^ but, nothing change, still the same issue

**Comment by bstascavage** [comment]
Run 'bin/getMachineID.rb' for me.

**Comment by mar7ius** [comment]
![user](https://cloud.githubusercontent.com/assets/10807969/6009021/5a3cf822-ab26-11e4-8df8-4bafa389bb6b.png)

**Comment by bstascavage** [comment]
Go to 'http://10.0.0.12/api/plexHueUser in a browser and post the output

**Comment by mar7ius** [comment]
{"lights":{"1":{"state": {"on":true,"bri":144,"hue":13123,"sat":212,"effect":"none","xy":[0.5125,0.4149],"ct":467,"alert":"none","colormode":"ct","reachable":true}, "type": "Extended color light", "name": "Hue Salon", "modelid": "LCT001","uniqueid":"00:17:88:01:00:fd:20:71-0b", "swversion": "66013452", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"2":{"state": {"on":true,"bri":144,"hue":13123,"sat":212,"effect":"none","xy":[0.5125,0.4149],"ct":467,"alert":"none","colormode":"ct","reachable":true}, "type": "Extended color light", "name": "SpotRight", "modelid": "LCT001","uniqueid":"00:17:88:01:00:ff:7a:eb-0b", "swversion": "66013452", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"3":{"state": {"on":true,"bri":144,"hue":13123,"sat":212,"effect":"none","xy":[0.5125,0.4149],"ct":467,"alert":"none","colormode":"ct","reachable":true}, "type": "Extended color light", "name": "SpotLeft", "modelid": "LCT001","uniqueid":"00:17:88:01:00:fd:27:3c-0b", "swversion": "66013452", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }}},"groups":{"1":{"name":"plex","lights":["2","3"],"type":"LightGroup","action": {"on":true,"bri":144,"hue":13123,"sat":212,"effect":"none","xy":[0.5125,0.4149],"ct":467,"colormode":"xy"}}},"config":{"name": "Philips hue","zigbeechannel": 15,"mac": "00:17:88:16:ba:03","dhcp": true,"ipaddress": "10.0.0.12","netmask": "255.255.255.0","gateway": "10.0.0.1","proxyaddress": "none","proxyport": 0,"UTC": "2015-02-02T21:04:43","localtime": "2015-02-02T22:04:43","timezone": "Europe/Paris","whitelist":{"Xe0vqkwrZIXds6As":{"last use date": "2015-02-02T20:45:35","create date": "2015-01-22T19:16:45","name": "Hue#iPhone Martial"},"XBG6YpaTlG1tjX1u":{"last use date": "2015-01-22T19:35:02","create date": "2015-01-22T19:31:56","name": "iPhone Martial"},"plexHueUser":{"last use date": "2015-02-02T21:04:43","create date": "2015-02-01T23:33:19","name": "plexHue"}},"swversion": "01018228","apiversion": "1.5.0","swupdate":{"updatestate": 0,"checkforupdate": false,"devicetypes": { "bridge": false, "lights": []},"url": "","text": "","notify": false},"linkbutton": false,"portalservices": true,"portalconnection": "connected","portalstate":{"signedon": true,"incoming": true,"outgoing": true,"communication": "connected"}},"schedules":{},"scenes":{"9b91fe11f-on-0":{"name":"Deep sea on 0","lights":["1","2","3"],"active":true},"33300ac17-on-0":{"name":"Feet up on 0","lights":["1","2","3"],"active":true},"bf4a3f8f4-on-0":{"name":"Laila on 0","lights":["1","2","3"],"active":true},"ac637e2f0-on-0":{"name":"DÃ©tente on 0","lights":["1","2","3"],"active":true},"e915785b2-on-0":{"name":"Lecture on 0","lights":["1","2","3"],"active":true},"84fa88aa5-on-0":{"name":"Stimulation on 0","lights":["1","2","3"],"active":true},"c4a83e4d1-on-1":{"name":"Pencils on 1","lights":["1","2","3"],"active":true},"84fa88aa5-on-10":{"name":"Stimulation on 1","lights":["1","2","3"],"active":true},"c81e728d9-off-5":{"name":"1 lights off","lights":["2"],"active":true},"022b4b0e3-on-0":{"name":"Films on 0","lights":["1","2","3"],"active":true},"62f8ac156-on-0":{"name":"Ski on 0","lights":["1","2","3"],"active":true}},"rules":{},"sensors":{"1":{"state": {"daylight":false,"lastupdated":"none"},"config":{"on":true,"long":"none","lat":"none","sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Philips","swversion":"1.0"}}}

**Comment by mar7ius** [comment]
I finally get the script run. It was an issue with my Ruby install, I reinstall ruby with ruby-build and now the script work well. Still got problems with the service, but it's a good start!

**Comment by bstascavage** [comment]
What is still wrong with it?

**Comment by mar7ius** [comment]
I don't know, still the same error than before, unless now, if I run the script plexHue.rb "manually" it works..
still have this error : 
![issue](https://cloud.githubusercontent.com/assets/10807969/6011326/efce82a2-ab3a-11e4-8bad-d10689fca46b.png)

**Comment by bstascavage** [comment]
That is because your distro doesn't have the /lib/init/vars.sh script.  You can comment that line out.

**Comment by bstascavage** [comment]
Is this still an issue?

**Comment by mar7ius** [comment]
No it's ok by now! thks for your help, and good luck for making improvement to this project!
